# Generated by Django 3.1.7 on 2021-02-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210223_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
