# Generated by Django 3.1.7 on 2021-03-06 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210226_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_reply', to='chat.message'),
        ),
    ]
